### ISSUE TITLE
The data table cuts on left and right sides in an ugly way

### ISSUE THREAD

**Issue by antonkulaga** [open-genes/open-genes-frontend#222]
The output table cuts on left and right on widescreen displays.
![cuts_on_sides](https://user-images.githubusercontent.com/842436/189242003-077573ce-635d-4a58-b1bf-410ce372fd32.png)

**Comment by const8ine** [comment]
Thank you for your issue! 
Some tables may be very wide so the truncation is made intentionally. Otherwise there is much space around. We will fix it, the viewport will be much wider. I see many people asking about this, we will denote that the table was cut in a more beautiful way.
The Studies page is now being refactored, this and many other issues will be fixed soon. 
As soon as we fix the truncation, we will notify you and close this issue.

**Comment by const8ine** [comment]
We fixed the bug by adding gradient shading to the left or right side of the container depending on the scroll position
